spring:
  application:
    name: tesouro-direto-api
  datasource:
    url: jdbc:h2:mem:tesouro
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console