CREATE TABLE INVESTIDOR (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTO (
    ID IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    RENTABILIDADE_ANUAL VARCHAR(50) NOT NULL,
    INVESTIMENTO_MINIMO NUMERIC(18, 2),
    PRECO_UNITARIO NUMERIC(18, 2),
    VENCIMENTO DATE
);

CREATE TABLE INVESTIDOR_PRODUTO (
    INVESTIDOR_ID VARCHAR(255) NOT NULL,
    PRODUTO_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (INVESTIDOR_ID, PRODUTO_ID),
    FOREIGN KEY (INVESTIDOR_ID) REFERENCES INVESTIDOR(ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);
